import type { ToolDefinition } from "./definitions.js";
import type { ExecutorKind, ToolAction, ToolDomain, ToolRisk } from "./catalog.js";

const obj=(properties:Record<string,unknown>,required:string[]=[])=>({type:"object",additionalProperties:false,properties,required});
const serverPlugin={server_plugin_id:{type:"string",format:"uuid"},reason:{type:["string","null"],maxLength:1000}};
const key={idempotency_key:{type:"string",minLength:16}};
function operation(name:string,domain:ToolDomain,action:ToolAction,risk:ToolRisk,executor:ExecutorKind,description:string,properties:Record<string,unknown>={},required:string[]=[]):ToolDefinition{
  const write=action!=="read";const backupConstrained=["backup_restore","deployment_snapshot_restore","database_optimize","database_import","database_search_replace","database_restore_snapshot","hosting_deploy","hosting_rollback","network_update_core_database","network_migrate_domain"].includes(name);return{name,version:1,category:write?"write":"read",isWrite:write,inputSchema:obj({...serverPlugin,...properties,...(write?key:{})},["server_plugin_id",...required,...(write?["idempotency_key"]:[])]),outputSchema:obj({operation_id:{type:"string",format:"uuid"},status:{type:"string"}},["operation_id","status"]),domain,action,risk,reversible:action!=="remove",executorKind:executor,credentialKinds:executor==="hosting"?["hosting_provider_token"]:["ssh_private_key"],supportsDryRun:name.includes("preview"),isLongRunning:true,description,...(backupConstrained?{constraintsSchema:obj({requiredBackupMaxAgeHours:{type:"integer",minimum:1,maximum:8760}})}:{})};
}
const id={id:{type:"string",format:"uuid"}};const name={name:{type:"string",minLength:1,maxLength:200}};
export const RECOVERY_TOOL_DEFINITIONS:ToolDefinition[]=[
  operation("backup_create","backups_recovery","create","high","database","Create a filesystem, database, or combined backup.",{kind:{type:"string",enum:["filesystem","database","combined"]},retention_days:{type:["integer","null"],minimum:1,maximum:3650}},["kind"]),
  operation("backup_list","backups_recovery","read","low","database","List backup inventory and retention metadata."),operation("backup_get","backups_recovery","read","low","database","Get backup metadata.",id,["id"]),
  operation("backup_verify","backups_recovery","operate","medium","database","Verify backup integrity.",id,["id"]),operation("backup_restore","backups_recovery","operate","critical","database","Restore a backup.",id,["id"]),
  operation("backup_delete","backups_recovery","remove","high","database","Delete a retained backup.",id,["id"]),operation("deployment_snapshot_create","backups_recovery","create","high","database","Create a deployment snapshot.",{...name},["name"]),
  operation("deployment_snapshot_restore","backups_recovery","operate","critical","database","Restore a deployment snapshot.",id,["id"]),
  operation("database_check","database","operate","medium","database","Check WordPress database tables."),operation("database_optimize","database","operate","high","database","Optimize WordPress database tables."),
  operation("database_export","database","create","high","database","Export the WordPress database."),operation("database_import","database","change","critical","database","Import a broker-managed database artifact.",id,["id"]),
  operation("database_list_tables","database","read","low","database","List table sizes and metadata."),operation("database_search_replace_preview","database","read","medium","database","Preview a serialization-aware search and replace.",{search:{type:"string"},replace:{type:"string"},network:{type:"boolean"}},["search","replace"]),
  operation("database_search_replace","database","change","critical","database","Run serialization-aware search and replace.",{search:{type:"string"},replace:{type:"string"},network:{type:"boolean"},backup_id:{type:["string","null"],format:"uuid"}},["search","replace"]),
  operation("database_restore_snapshot","database","operate","critical","database","Restore a linked database snapshot.",id,["id"])
];

export const HOSTING_TOOL_DEFINITIONS:ToolDefinition[]=[
  operation("hosting_deploy","hosting_deployment","operate","critical","hosting","Deploy through a reviewed hosting adapter.",{environment:{type:"string"},reference:{type:["string","null"]}},["environment"]),operation("hosting_rollback","hosting_deployment","operate","critical","hosting","Roll back a provider deployment.",id,["id"]),
  operation("hosting_clone_environment","hosting_deployment","create","critical","hosting","Clone a provider environment.",{source:{type:"string"},target:{type:"string"}},["source","target"]),operation("hosting_set_domain","hosting_deployment","change","high","hosting","Set a provider-managed domain.",{domain:{type:"string"}},["domain"]),
  operation("hosting_manage_certificate","hosting_deployment","operate","high","hosting","Issue or renew a provider certificate.",{domain:{type:"string"}},["domain"]),operation("hosting_flush_cache","hosting_deployment","operate","medium","hosting","Flush provider cache."),
  operation("hosting_create_snapshot","hosting_deployment","create","high","hosting","Create a provider snapshot."),operation("hosting_get_runtime","hosting_deployment","read","low","hosting","Read provider runtime metadata."),operation("hosting_get_deployment_logs","hosting_deployment","read","medium","hosting","Read bounded deployment logs.",id,["id"])
];

export const MULTISITE_TOOL_DEFINITIONS:ToolDefinition[]=[
  operation("network_list_sites","multisite","read","medium","wp_cli","List servers in a WordPress network."),operation("network_create_site","multisite","create","critical","wp_cli","Create a network serverPlugin.",{slug:{type:"string"},title:{type:"string"},email:{type:"string"}},["slug","title","email"]),
  operation("network_update_site","multisite","change","critical","wp_cli","Change network serverPlugin metadata.",{blog_id:{type:"integer"},domain:{type:["string","null"]},path:{type:["string","null"]}},["blog_id"]),operation("network_archive_site","multisite","operate","critical","wp_cli","Archive or unarchive a network serverPlugin.",{blog_id:{type:"integer"},archived:{type:"boolean"}},["blog_id","archived"]),operation("network_delete_site","multisite","remove","critical","wp_cli","Permanently delete a network serverPlugin.",{blog_id:{type:"integer"}},["blog_id"]),
  operation("network_list_super_admins","multisite","read","high","wp_cli","List network Super Admins."),operation("network_grant_super_admin","multisite","operate","critical","wp_cli","Grant downstream Super Admin status.",{user:{type:"string"}},["user"]),operation("network_revoke_super_admin","multisite","operate","critical","wp_cli","Revoke downstream Super Admin status.",{user:{type:"string"}},["user"]),
  operation("network_activate_plugin","multisite","operate","critical","wp_cli","Network-activate a plugin.",name,["name"]),operation("network_deactivate_plugin","multisite","operate","high","wp_cli","Network-deactivate a plugin.",name,["name"]),operation("network_update_plugin","multisite","change","high","wp_cli","Update a network plugin.",name,["name"]),operation("network_enable_theme","multisite","operate","high","wp_cli","Network-enable a theme.",name,["name"]),
  operation("network_assign_user","multisite","operate","high","wp_cli","Assign a user to a network serverPlugin.",{site_url:{type:"string"},user:{type:"string"},role:{type:"string"}},["site_url","user","role"]),operation("network_update_core_database","multisite","change","critical","wp_cli","Update the network database schema."),operation("network_migrate_domain","multisite","change","critical","wp_cli","Migrate controlled network domain/path metadata.",{old_url:{type:"string"},new_url:{type:"string"}},["old_url","new_url"])
];
